### ISSUE TITLE
authorization by token

### ISSUE THREAD

**Issue by awasilyev** [qubell/contrib-python-qubell-client#231]
It will be very useful to have aws-like authorization by token instead of user/password. 
Tokens can be generated in the ui and then used in the console client.

This will solve problem of accessing accounts, authorized with google auth.

**Comment by storgashov** [comment]
@vasichkin, @awasilyev, does #259 solve the issue?

**Comment by vasichkin** [comment]
I think yes

**Comment by storgashov** [comment]
Resolved in #259.
